services:
  - type: web
    runtime: static
    name: barfly-mystery-files
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
